name: runwx
version: '1.0.0'
config-version: 2
profile: runwx

flags:
  send_anonymous_usage_stats: false

model-paths: [models]
test-paths: [tests]
macro-paths: [macros]

vars:
  top_n: 20

models:
  runwx:
    +materialized: view
